version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
  exclusions:
    paths:
      - cmd/ghost-wispr/static

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/sjawhar/ghost-wispr
